### ISSUE TITLE
Is it possible to edit/refine mAb Fv sequence from an Alphafold2 multimer mAb/antigen pdb?

### ISSUE THREAD

**Issue by avilella** [BioinfoMachineLearning/DeepRefine#1]
Is it possible to use this tool to edit/refine the mAb Fv sequence from an Alphafold2 multimer mAb/antigen pdb?
We don't know if the multimer prediction is perfect, but we know from epitope mapping that is close to the correct solution.

**Comment by amorehead** [comment]
@avilella,

Thank you for expressing interest in our work here! Currently, DeepRefine focuses on performing 3D structural refinement of multimeric proteins. Sequence refinement is not implemented in this pipeline as of yet, however, your question does raise an interesting question of whether the techniques we present in our DeepRefine manuscript may be used for per-token sequence refinement as well.

If I simply misunderstood your original question, it may be worth trying to refine the mAb Fv sequence's 3D structure by treating it as the first (or second) chain in the multimer. I will point out, however, that the model is not trained on antibody-focused data sources, so you will want to sanity-check the results of DeepRefine's 3D refinement by manually inspecting the new structure after the fact.

Best of luck in your endeavors here!

**Comment by avilella** [comment]
Thanks. I'll keep an eye on the repo.
