### ISSUE TITLE
Refinement of non-protein residues

### ISSUE THREAD

**Issue by jadolfbr** [BioinfoMachineLearning/DeepRefine#3]
Hello,

I was wondering if your method would work for non-canonical amino acids and proteins bound to non-protein ligands. Thanks.

**Comment by amorehead** [comment]
Hi, @jadolfbr. We have not tested our method for this use case. In principle as long as your input molecules/proteins contain PDB `atom types` corresponding to one of the following atom types, our method should be compatible with such inputs. I hope this helps.

```
PROT_ATOM_NAMES = ['N', 'CA', 'C', 'O', 'CB', 'OG', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ', 'OD1', 'ND2', 'CG1', 'CG2',
                   'CD', 'CE', 'NZ', 'OD2', 'OE1', 'NE2', 'OE2', 'OH', 'NE', 'NH1', 'NH2', 'OG1', 'SD', 'ND1', 'SG',
                   'NE1', 'CE3', 'CZ2', 'CZ3', 'CH2', 'OXT', 'UNX']  # 'UNX' represents the unknown atom type
```
